name: CI
on:
  push:
    branches-ignore:
      - 'update-dependencies'
      - 'dependabot/*'
  pull_request:
env:
  PY_COLORS: "1"
  MYPY_FORCE_TERMINAL_WIDTH: "180"

jobs:
  tests:
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    timeout-minutes: 45
    continue-on-error: "${{ matrix.experimental == true }}"
    strategy:
      fail-fast: false
      matrix:
        include:
          ### Windows: PyQt 5.15 (Python 3.7 to match PyInstaller env)
          - testenv: py37-pyqt515
            os: windows-2019
            python: 3.7
            n: 1
          - testenv: py37-pyqt515
            os: windows-2019
            python: 3.7
            n: 2
          - testenv: py37-pyqt515
            os: windows-2019
            python: 3.7
            n: 3
          - testenv: py37-pyqt515
            os: windows-2019
            python: 3.7
            n: 4
          - testenv: py37-pyqt515
            os: windows-2019
            python: 3.7
            n: 5
          - testenv: py37-pyqt515
            os: windows-2019
            python: 3.7
            n: 6
          - testenv: py37-pyqt515
            os: windows-2019
            python: 3.7
            n: 7
          - testenv: py37-pyqt515
            os: windows-2019
            python: 3.7
            n: 8
          - testenv: py37-pyqt515
            os: windows-2019
            python: 3.7
            n: 9
          - testenv: py37-pyqt515
            os: windows-2019
            python: 3.7
            n: 10
    runs-on: "${{ matrix.os }}"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            .mypy_cache
            .tox
            ~/.cache/pip
          key: "${{ matrix.testenv }}-${{ matrix.os }}-${{ matrix.python }}-${{ hashFiles('misc/requirements/requirements-*.txt') }}-${{ hashFiles('requirements.txt') }}"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python }}"
      - name: Set up problem matchers
        run: "python scripts/dev/ci/problemmatchers.py ${{ matrix.testenv }} ${{ runner.temp }}"
      - name: Install apt dependencies
        run: |
            sudo apt-get update
            sudo apt-get install --no-install-recommends libyaml-dev libegl1-mesa libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0
        if: "startsWith(matrix.os, 'ubuntu-')"
      - name: Install dependencies
        run: |
            python -m pip install -U pip
            python -m pip install -U -r misc/requirements/requirements-tox.txt
      - name: "Run ${{ matrix.testenv }}"
        run: "tox -e ${{ matrix.testenv}} -- ${{ matrix.args }}"
